#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Mentor Graphics Questa Advanced Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 01 12:50:05 +0530 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/home/sachith/Questa.2022.2/questasim/linux_x86_64"
set -Eeuo pipefail
$bin_path/vsim -64 -c -do "do {tb_top_simulate.do}" -l simulate.log

