######################################################################
#
# File name : tb_top_simulate.do
# Created on: Fri Dec 01 12:50:05 +0530 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_wave.do}

view wave
view structure
view signals

do {tb_top.udo}

run -all

quit -force
