######################################################################
#
# File name : tb_top_elaborate.do
# Created on: Fri Dec 01 12:50:05 +0530 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L axis_infrastructure_v1_1_0 -L axi4stream_vip_v1_1_13 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl -o tb_top_opt
