######################################################################
#
# File name : tb_top_wave.do
# Created on: Fri Dec 01 12:50:05 +0530 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
