#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Dec 01 12:57:44 +0530 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
# export XILINX_VIP_INCLUDE_PATH=/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include
echo "$XILINX_VIP_INCLUDE_PATH"
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi4stream_vip_v1_1_13 -L xilinx_vip -prj tb_top_vlog.prj"
xvlog --incr --relax -L uvm -L axi4stream_vip_v1_1_13 -L xilinx_vip -prj tb_top_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
